### ISSUE TITLE
Causing a server to crash on startup (1.19.2)

### ISSUE THREAD

**Issue by QueenDiancieTTV** [UnlikePaladin/netherite-cake#7]
Here is the crashlogs

```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2023-12-27 13:37:33
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.3.5-universal.jar%23338!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.3.5-universal.jar%23338!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23333!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD ncake --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/registries/IForgeRegistryEntry
		at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
		at java.lang.Class.forName(Class.java:467) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.3.5.jar%23335!/:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.3.5.jar%23335!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:85) ~[javafmllanguage-1.19.2-43.3.5.jar%23335!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.3.5.jar%23334!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /home/minecraft/multicraft/servers/server573323/mods/netherite_cake-1.3.0-1.19.x.jar
	Failure message: Netherite Cake Mod (ncake) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/registries/IForgeRegistryEntry
	Mod Version: 1.3.0
	Mod Issue URL: https://github.com/UnlikePaladin/netherite-cake/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.registries.IForgeRegistryEntry
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.forName(Class.java:467) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.3.5.jar%23335!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.3.5.jar%23335!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:85) ~[javafmllanguage-1.19.2-43.3.5.jar%23335!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.3.5.jar%23334!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 4.18.0-348.2.1.el8_5.x86_64
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 513941776 bytes (490 MiB) / 1358954496 bytes (1296 MiB) up to 12582912000 bytes (12000 MiB)
	CPUs: 5
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 64185.07
	Virtual memory used (MB): 57616.13
	Swap memory total (MB): 32255.99
	Swap memory used (MB): 24856.76
	JVM Flags: 5 total; -Xmx12000M -Xms128M -XX:MaxDirectMemorySize=256M -XX:MaxMetaspaceSize=1024M -XX:MaxRAMPercentage=90.0
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		kotori_scala@2.13.10-build-10
		javafml@null
	Mod List: 
		ftb-essentials-1902.1.10-build.47.jar             |FTB Essentials                |ftbessentials                 |1902.1.10-build.47  |COMMON_SET|Manifest: NOSIGNATURE
		AdditionalEnchantedMiner-1.19.2-1192.3.25.jar     |QuarryPlus                    |quarryplus                    |1192.3.25           |COMMON_SET|Manifest: ef:50:af:b3:03:e0:3e:70:a7:ef:78:77:a5:4d:d4:b5:07:ec:df:9d:d6:f3:12:13:c9:3c:cd:9a:0a:3e:6b:43
		player-animation-lib-forge-1.0.2.jar              |Player Animator               |playeranimator                |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		aether-1.19.2-1.0.0-beta.2.2-forge.jar            |The Aether                    |aether                        |1.19.2-1.0.0-beta.2.|COMMON_SET|Manifest: NOSIGNATURE
		HammerLib-1.19.2-19.3.74.jar                      |HammerLib                     |hammerlib                     |19.3.74             |COMMON_SET|Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		ProjectE-1.19.2-PE1.1.0.jar                       |ProjectE                      |projecte                      |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-windows-2.2.1-mc1.19.2forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		ProjectExpansion-1.19.2-1.0.10.jar                |Project Expansion             |projectexpansion              |1.19.2-1.0.10       |COMMON_SET|Manifest: 16:32:1c:48:e2:f7:71:f1:1b:23:7f:74:d8:e6:89:43:6a:a8:33:8f:49:17:6a:11:19:cd:66:4b:88:c1:02:19
		Industrial Agriculture[Core]-1.19.2-1.9.1.jar     |Industrial Agriculture        |industrialagriculture         |1.19.2-1.9.1        |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.19.2-0.5.109.516.jar          |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.109.516  |COMMON_SET|Manifest: NOSIGNATURE
		structureessentials-1.19.2-3.2.jar                |Structure Essentials mod      |structureessentials           |1.19.2-3.2          |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.37.2_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.37.2              |COMMON_SET|Manifest: NOSIGNATURE
		CTM-1.19.2-1.1.6+8.jar                            |ConnectedTexturesMod          |ctm                           |1.19.2-1.1.6+8      |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.1.4-1.19.jar                            |Citadel                       |citadel                       |2.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.9.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.9        |COMMON_SET|Manifest: NOSIGNATURE
		waystone_towers-1.19.2-FORGE-1.0.9.jar            |Waystone Towers               |waystone_towers               |1.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		BotanyPotsTiers-Forge-1.19.2-3.3.2.jar            |BotanyPotsTiers               |botanypotstiers               |3.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.3.20.jar                |Bookshelf                     |bookshelf                     |16.3.20             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.19.2-3.19.4.977.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.19.4.977   |COMMON_SET|Manifest: NOSIGNATURE
		mcw-doors-1.1.0forge-mc1.19.2.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.6.0.jar                       |Balm                          |balm                          |4.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		chat_heads-0.10.27-forge-1.19.2.jar               |Chat Heads                    |chat_heads                    |0.10.27             |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-8.3.103-forge.jar                    |Cloth Config v8 API           |cloth_config                  |8.3.103             |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.4.14.jar                 |Supplementaries               |supplementaries               |1.19.2-2.4.14       |COMMON_SET|Manifest: NOSIGNATURE
		EnemyExpansion-1.19.2-2.0.0.jar                   |Enemy Expansion               |enemyexpansion                |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		corpse-1.19.2-1.0.9.jar                           |Corpse                        |corpse                        |1.19.2-1.0.9        |COMMON_SET|Manifest: NOSIGNATURE
		chipped-forge-1.19.2-2.1.5.jar                    |Chipped                       |chipped                       |2.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		xaeros_waystones_compability-1.0.jar              |Xaero's Map - Waystones Compab|w2w2                          |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		mcw-bridges-2.1.1-mc1.19.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.19.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.3        |COMMON_SET|Manifest: NOSIGNATURE
		BotanyTrees-Forge-1.19.2-5.0.12.jar               |BotanyTrees                   |botanytrees                   |5.0.12              |COMMON_SET|Manifest: NOSIGNATURE
		explorify-forge-1.19-1.3.0.jar                    |Explorify                     |explorify                     |1.19-1.3.0          |COMMON_SET|Manifest: NOSIGNATURE
		mcw-trapdoors-1.1.2-mc1.19.2forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.19.2forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.16-forge-mc1.19.2.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.16              |COMMON_SET|Manifest: NOSIGNATURE
		Botania-1.19.2-440-FORGE.jar                      |Botania                       |botania                       |1.19.2-440-FORGE    |COMMON_SET|Manifest: NOSIGNATURE
		born_in_chaos_[Forge]1.19.2_1.9.jar               |Born in Chaos                 |born_in_chaos_v1              |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		MysticalAdaptations-1.19.2-1.0.jar                |Mystical Adaptations          |mysticaladaptations           |1.19.2-1.0          |COMMON_SET|Manifest: NOSIGNATURE
		SolarFluxReborn-1.19.2-19.3.10.jar                |Solar Flux Reborn             |solarflux                     |19.3.10             |COMMON_SET|Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		curios-forge-1.19.2-5.1.4.3.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.3      |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |COMMON_SET|Manifest: NOSIGNATURE
		corail_woodcutter-1.19.2-2.5.2.jar                |Corail Woodcutter             |corail_woodcutter             |2.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		elevatorid-1.19.2-1.8.10.jar                      |Elevator Mod                  |elevatorid                    |1.19.2-1.8.10       |COMMON_SET|Manifest: NOSIGNATURE
		Gobber2-Forge-1.19.2-2.7.28.jar                   |Gobber 2                      |gobber2                       |2.7.28              |COMMON_SET|Manifest: NOSIGNATURE
		ftb-ultimine-forge-1902.4.1-build.90.jar          |FTB Ultimine                  |ftbultimine                   |1902.4.1-build.90   |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-forge-1.19.2-1.1.24.jar            |Resourceful Lib               |resourcefullib                |1.1.24              |COMMON_SET|Manifest: NOSIGNATURE
		cumulus_menus-1.19.2-1.0.0-beta.1-forge.jar       |Cumulus                       |cumulus_menus                 |1.19.2-1.0.0-beta.1-|COMMON_SET|Manifest: NOSIGNATURE
		mcw-roofs-2.2.4-mc1.19.2forge.jar                 |Macaw's Roofs                 |mcwroofs                      |2.2.4               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.5.85-forge.jar                     |Architectury                  |architectury                  |6.5.85              |COMMON_SET|Manifest: NOSIGNATURE
		squatgrow-3.0.1+mc1.19.2.jar                      |Squat Grow                    |squatgrow                     |3.0.1+mc1.19.2      |COMMON_SET|Manifest: NOSIGNATURE
		cc-tweaked-1.19.2-1.101.3.jar                     |CC: Tweaked                   |computercraft                 |1.101.3             |COMMON_SET|Manifest: NOSIGNATURE
		mcw-furniture-3.2.1-mc1.19.2forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		cupboard-1.19.2-2.1.jar                           |Cupboard utilities            |cupboard                      |1.19.2-2.1          |COMMON_SET|Manifest: NOSIGNATURE
		nitrogen_internals-1.19.2-0.3.0-forge.jar         |Nitrogen                      |nitrogen_internals            |1.19.2-0.3.0-forge  |COMMON_SET|Manifest: NOSIGNATURE
		JadeAddons-1.19.2-forge-3.6.0.jar                 |Jade Addons                   |jadeaddons                    |3.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		EnchantingInfuser-v4.2.2-1.19.2-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |4.2.2               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		mcw-lights-1.0.6-mc1.19.2forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		elytraslot-forge-6.1.1+1.19.2.jar                 |Elytra Slot                   |elytraslot                    |6.1.1+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		royalcrowns-1.2.5.jar                             |Royal Crowns                  |royalcrowns                   |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Cucumber-1.19.2-6.0.10.jar                        |Cucumber Library              |cucumber                      |6.0.10              |COMMON_SET|Manifest: NOSIGNATURE
		ftb-library-forge-1902.4.1-build.236.jar          |FTB Library                   |ftblibrary                    |1902.4.1-build.236  |COMMON_SET|Manifest: NOSIGNATURE
		ftb-teams-forge-1902.2.14-build.123.jar           |FTB Teams                     |ftbteams                      |1902.2.14-build.123 |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedstorage-1.19.2-0.8.54.670.jar        |Sophisticated Storage         |sophisticatedstorage          |1.19.2-0.8.54.670   |COMMON_SET|Manifest: NOSIGNATURE
		additionallanterns-1.1.1-forge-mc1.19.jar         |Additional Lanterns           |additionallanterns            |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		xlpackets-1.18.2-2.1.jar                          |XL Packets                    |xlpackets                     |1.18.2-2.1          |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1018.jar                  |Just Enough Items             |jei                           |11.6.0.1018         |COMMON_SET|Manifest: NOSIGNATURE
		Pehkui-3.7.11+1.19.2-forge.jar                    |Pehkui                        |pehkui                        |3.7.11+1.19.2-forge |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.4.2.jar                 |Waystones                     |waystones                     |11.4.2              |COMMON_SET|Manifest: NOSIGNATURE
		netherite_cake-1.3.0-1.19.x.jar                   |Netherite Cake Mod            |ncake                         |1.3.0               |ERROR     |Manifest: NOSIGNATURE
		mcw-paintings-1.0.5-1.19.2forge.jar               |Macaw's Paintings             |mcwpaintings                  |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.19.2-9.0.0+14.jar                  |Clumps                        |clumps                        |9.0.0+14            |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-6.0.6+1.19.2.jar                   |Comforts                      |comforts                      |6.0.6+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.19.2-1.10.0-forge.jar            |Nature's Compass              |naturescompass                |1.19.2-1.10.0-forge |COMMON_SET|Manifest: NOSIGNATURE
		untamedwilds-1.19.2-3.0.4.jar                     |Untamed Wilds                 |untamedwilds                  |3.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		untameddelight-1.19.2-1.0.0.jar                   |Untamed Delight               |untameddelight                |1.19.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		badpackets-forge-0.2.3.jar                        |Bad Packets                   |badpackets                    |0.2.3               |COMMON_SET|Manifest: NOSIGNATURE
		BotanyPots-Forge-1.19.2-9.0.38.jar                |BotanyPots                    |botanypots                    |9.0.38              |COMMON_SET|Manifest: NOSIGNATURE
		lazydfu-1.19-1.0.2.jar                            |LazyDFU                       |lazydfu                       |0.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		everycomp-1.19.2-2.5.15.jar                       |Every Compat                  |everycomp                     |1.19.2-2.5.15       |COMMON_SET|Manifest: NOSIGNATURE
		ExplorersCompass-1.19.2-1.3.0-forge.jar           |Explorer's Compass            |explorerscompass              |1.19.2-1.3.0-forge  |COMMON_SET|Manifest: NOSIGNATURE
		projecte-integration-1.19.2-6.3.3.jar             |ProjectE Integration          |projecteintegration           |6.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		fusion-1.1.0b-forge-mc1.19.2.jar                  |Fusion                        |fusion                        |1.1.0b              |COMMON_SET|Manifest: NOSIGNATURE
		CraftTweaker-forge-1.19.2-10.1.52.jar             |CraftTweaker                  |crafttweaker                  |10.1.52             |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-1.19.2-10.3.9.13.jar                     |Mekanism                      |mekanism                      |10.3.9              |COMMON_SET|Manifest: NOSIGNATURE
		ftb-chunks-forge-1902.4.2-build.302.jar           |FTB Chunks                    |ftbchunks                     |1902.4.2-build.302  |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.3.5-universal.jar                 |Forge                         |forge                         |43.3.5              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		silent-gear-1.19.2-3.2.2.jar                      |Silent Gear                   |silentgear                    |3.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-paths-1.0.3forge-mc1.19.2.jar                 |Macaw's Paths and Pavings     |mcwpaths                      |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		emotecraft-for-MC1.19.2-2.2.5-forge.jar           |Emotecraft                    |emotecraft                    |2.2.5               |COMMON_SET|Manifest: NOSIGNATURE
		MysticalAgriculture-1.19.2-6.0.13.jar             |Mystical Agriculture          |mysticalagriculture           |6.0.13              |COMMON_SET|Manifest: NOSIGNATURE
		MysticalAgradditions-1.19.2-6.0.3.jar             |Mystical Agradditions         |mysticalagradditions          |6.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		matc-1.3.1.jar                                    |Mystical Agriculture Tiered Cr|matc                          |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.19.2-2.1.54-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.54-1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
		server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.2-2.0.1.136.jar           |TerraBlender                  |terrablender                  |2.0.1.136           |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.3.5-forge.jar                  |Moonlight Library             |moonlight                     |1.19.2-2.3.5        |COMMON_SET|Manifest: NOSIGNATURE
		silent-lib-1.19.2-7.0.3.jar                       |Silent Lib                    |silentlib                     |7.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.9.1.jar                       |Jade                          |jade                          |8.9.1               |COMMON_SET|Manifest: NOSIGNATURE
		appliedenergistics2-forge-12.9.8.jar              |Applied Energistics 2         |ae2                           |12.9.8              |COMMON_SET|Manifest: NOSIGNATURE
		CroptopiaDelight-1.19.2_1.2.2-forge.jar           |Croptopia Delight             |croptopiadelight              |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		spectrelib-forge-0.12.6+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.6+1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
		easy_villagers-1.19.2-1.0.17.jar                  |Easy Villagers                |easy_villagers                |1.19.2-1.0.17       |COMMON_SET|Manifest: NOSIGNATURE
		plushies-1.2-1.19.2.jar                           |Plushie Mod                   |plushies                      |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
		gobber_delight_2.0.0_forge_1.19.2.jar             |Gobber Delight (by NoCube)    |gobberdelight                 |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_23.9.3_Forge_1.19.1.jar            |Xaero's Minimap               |xaerominimap                  |23.9.3              |COMMON_SET|Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-0.46.5+1.19.2.jar                 |Polymorph                     |polymorph                     |0.46.5+1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
		[1.19.2] SecurityCraft v1.9.6.1.jar               |SecurityCraft                 |securitycraft                 |1.9.6.1             |COMMON_SET|Manifest: NOSIGNATURE
		UniversalEnchants-v4.2.15-1.19.2-Forge.jar        |Universal Enchants            |universalenchants             |4.2.15              |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
		alexsdelight-1.4.1.jar                            |Alex's Delight                |alexsdelight                  |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		lootr-1.19-0.4.24.64.jar                          |Lootr                         |lootr                         |0.4.24.63           |COMMON_SET|Manifest: NOSIGNATURE
		connectedglass-1.1.10-forge-mc1.19.jar            |Connected Glass               |connectedglass                |1.1.10              |COMMON_SET|Manifest: NOSIGNATURE
		moredragoneggs-3.2.jar                            |More Dragon Eggs              |moredragoneggs                |3.2                 |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v4.4.3-1.19.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |4.4.3               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.6.jar  |Oh The Biomes You'll Go       |byg                           |2.0.1.6             |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
		CorgiLib-forge-1.19.2-1.0.0.34.jar                |CorgiLib                      |corgilib                      |1.0.0.34            |COMMON_SET|Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.19.2-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19.2-v1a          |COMMON_SET|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		BotanyPotsOrePlanting-Forge-3.11.0+1.19.2.jar     |Botany Pots Ore Planting      |botany_pots_ore_planting      |3.11.0              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 6046c6c3-4be4-466a-a2a2-08cf7d7a86c9
	FML: 43.3
	Forge: net.minecraftforge:43.3.5
```

**Comment by Sylvezar** [comment]
[crash-2023-12-27_16.56.08-fml.txt](https://github.com/UnlikePaladin/ored-cakes/files/13779730/crash-2023-12-27_16.56.08-fml.txt)
the same happens with a clean server.

> Failure message: Netherite Cake Mod (ncake) has failed to load correctly
>                 java.lang.NoClassDefFoundError: net/minecraftforge/registries/IForgeRegistryEntry
